#![allow(nonstandard_style)]
pub mod apartments;
pub mod collecting_numbers;
pub mod collecting_numbers_II;
pub mod concert_tickets;
pub mod distinct_numbers;
pub mod distinct_values_subarrays;
pub mod distinct_values_subsequences;
pub mod ferris_wheel;
pub mod josephus_problem_I;
pub mod maximum_subarray_sum;
pub mod missing_coin_sum;
pub mod movie_festival;
pub mod playlist;
pub mod restaurant_customers;
pub mod stick_lengths;
pub mod sum_of_two_values;
pub mod towers;
pub mod traffic_lights;
